### ISSUE TITLE
Default block_size

### ISSUE THREAD

**Issue by davidweichiang** [bdusell/semiring-einsum#6]
Or can the documentation at least recommend a good block_size?

**Comment by bdusell** [comment]
This question has [come up before](https://github.com/bdusell/semiring-einsum/issues/1), and I should finally add a note about it. I purposely required the user to provide a `block_size` because the right value really depends on their application and resources. It also depends on the number of variables being summed out; if there are `n` variables, then the size of the block tensor is `block_size ** n`. When in doubt, a value of `10` is a good place to start.

**Comment by davidweichiang** [comment]
Following up on this...maybe it would be more user friendly if they could specify that the temporary space usage is some constant number of floats, or some multiple of the size of the inputs and outputs?

**Comment by bdusell** [comment]
I've now implemented a default block size based on available GPU memory. On CPU, it chooses a block size that does not exceed 1 GiB.

**Comment by davidweichiang** [comment]
Cool! Is it the case that PyTorch runs only one einsum at a time, so it's safe to use all available memory?
